Fri Mar  1 05:41:39 UTC 2013 ap/groff-1.22.2-x86_64-1.txz:  Upgraded. x/fontconfig-2.10.2-x86_64-2.txz:  Rebuilt.   Fixed dangling symlink to 20-fix-globaladvance.conf (which was removed).   Create the symlinks in doinst.sh before running fc-cache.   Don't include /usr/share/fonts in the fonts.conf font directory list as that   causes bitmapped fonts to be used.  Thanks to Iouri Kharon.

diff --git a/x/fontconfig/fontconfig.SlackBuild b/x/fontconfig/fontconfig.SlackBuild
--- a/x/fontconfig/fontconfig.SlackBuild
+++ b/x/fontconfig/fontconfig.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2008, 2009, 2010  Patrick J. Volkerding, Sebeka, Minnesota, USA
+# Copyright 2008, 2009, 2010, 2013  Patrick J. Volkerding, Sebeka, Minnesota, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,7 +22,7 @@
 
 
 VERSION=${VERSION:-$(echo fontconfig-*.tar.?z* | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
@@ -133,7 +133,6 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
 # Set up the default options in /etc/fonts/conf.d:
 (  cd $PKG/etc/fonts/conf.d
    for fontconf in \
-        20-fix-globaladvance.conf \
         20-unhint-small-vera.conf \
         30-urw-aliases.conf \
         30-metric-aliases.conf \
@@ -148,7 +147,12 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
         69-unifont.conf \
         80-delicious.conf \
         90-synthetic.conf ; do
-     ln -sf ../conf.avail/$fontconf . || exit 1
+     if [ -r ../conf.avail/$fontconf ]; then
+       ln -sf ../conf.avail/$fontconf .
+     else
+       echo "ERROR:  unable to symlink ../conf.avail/$fontconf, file does not exist."
+       exit 1
+     fi
    done
    if [ ! $? = 0 ]; then
      exit 1
@@ -179,5 +183,5 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/fontconfig-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n --prepend $TMP/fontconfig-$VERSION-$ARCH-$BUILD.txz
 
